---
galaxy_info:
    author: "MichaÃ«l Val contrib Indelog"
    description: 'This Ansible role install the latest version of MedShakeEHR'
    license: GPL-3.0-only
    min_ansible_version: '2.9'
    platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
dependencies: 
  - role: geerlingguy.php
  - role: geerlingguy.mysql