---
timezone: "Europe/Paris"
msehr_package: ['acl','curl','ghostscript','git','grub','imagemagick','ntp','pdftk','python3-openssl','wget']
msehrPath: "/home/ehr"
msehr_base_repo_url: "https://codeload.github.com/MedShake/MedShakeEHR-base/tar.gz/refs/tags/"
msehr_base_release: "7.1.1"
msehr_base_checksum: "sha256:8f13f4f3d6e3de6c9d5e3c9de52dd3683909067d0b01c60d6cbf32e530526a2d"
create_self_signed_cert: true
countryName: FR
localityName: Paris
organizationName: Dr Strange
emailAdress: email@domain.tld
orthancUser: user
orthancPswd: orthancPswd
